### ISSUE TITLE
higher restitution causes collisions to deal more damage

### ISSUE THREAD

**Issue by Tim2othy** [Tim2othy/spacegame#14]
Currently the damage dealt to the ship if it hits a planet is a function of the restitution. It shouldn't matter how fast the ship is after the impact only before. The damage should probably only depend on self_vel_along_normal.

If anything, higher restitution should lead to less damage.

**Comment by Tim2othy** [comment]
now self_vel_along_normal  is also returned by bounce_off_of_disk (and the next method) and self_vel_along_normal value is used in apply_bounce to calculate the damage, so the restitution isn't used anymore for this calculation.

**Comment by lumi-a** [comment]
We need not return the `impulse_scalar` at all, as it's never used for any calculations.

**Comment by lumi-a** [comment]
Fixed in aa4d125c9895378dd54d42bec9000aac77f3bfa9
