### ISSUE TITLE
Projectile Lifetime

### ISSUE THREAD

**Issue by lumi-a** [Tim2othy/spacegame#15]
So that projectiles don't clutter up the screen too much (especially Rockets), they should have a `lifetime`-attribute, and fade out of existence once that attribute approaches some `MAX_LIFETIME`. (Does pygame permit transparency drawing?)

**Comment by Tim2othy** [comment]
Sounds good.

For the rockets i think it's cool if they can accelerate towards the player around 5 times and then they just keep going straight ahead. And then a little later they can despawn.

I don't think transparency is so good, I'd rather they disappear after some time if they are also not on the player's screen and haven't been there recently.

**Comment by lumi-a** [comment]
Currently, they're always on the minimap, as long as they're still in-universe. Should that count as being "on the player's screen"? If so, we might as well only delete them once they reach the universe's edge, which would take forever with huge universes.

**Comment by Tim2othy** [comment]
In test mode (where the universe is smaller) there are generally <200 enemy projectiles on the screen. And player projectiles also reach the edge of the universe in around 4 seconds. I don't think we have to worry about this for now.
