### ISSUE TITLE
Spaceguns

### ISSUE THREAD

**Issue by lumi-a** [Tim2othy/spacegame#16]
You used to have Spaceguns. Would you like to revive those?

I think they could inherit from `pygame.Rect`. Maybe we should create a class `Ship` that doesn't inherit from `Disk`, and have:
- Existing ships inherit from `Disk` and the new `Ship`-class
- Spacegun inherit from `pygame.Rect` and `Ship`.

**Comment by Tim2othy** [comment]
I don't think we need them for now, they would just be enemies except that they can't move.
