### ISSUE TITLE
Projectile-Planet-Interactions

### ISSUE THREAD

**Issue by lumi-a** [Tim2othy/spacegame#17]
Currently, bullets get destroyed when hitting a planet/asteroid, and aren't affected by gravity.
- It'd be inexpensive to have bullets bounce off of a planet/asteroid, and might allow the player to pull off some cool moves.
- It'd be possible, but more expensive, to have Bullets be affected by gravity. Perhaps only feasible after #11

**Comment by Tim2othy** [comment]
for now, I'd leave it like this, think of bullets as lasers mostly not affected by gravity and they disappear if they touch a planet.
