### ISSUE TITLE
Constants in Code

### ISSUE THREAD

**Issue by lumi-a** [Tim2othy/spacegame#19]
Currently, constants are all over the place in code. Some are at the top of modules, some are just in the class `__init__`. Find out what the most pythonic way to manage such constants is, and implement it.

**Comment by Tim2othy** [comment]
created and moved constants to constants.py 58a5aaa.

I guess that the list of all the planets is basically also a constant and also belongs there. I also moved the for loops that create the lists of enemies and asteroids there, but maybe they should stay in main.

**Comment by Tim2othy** [comment]
It doesn't seem good if `constants.py` has to import tons of classes from other files, so I moved initialization of the playerships, planets, asteroids, enemies and all the testmode stuff to where it was before in `main`. Now `constants` doesn't depend on any other files.

**Comment by Tim2othy** [comment]
It doesn't seem good if `constants.py` has to import tons of classes from other files, so I moved initialization of the playerships, planets, asteroids, enemies and all the testmode stuff to where it was before in `main`. Now `constants` doesn't depend on any other files.
