### ISSUE TITLE
Make Minimap work with large World

### ISSUE THREAD

**Issue by Tim2othy** [Tim2othy/spacegame#27]
the minimap has quite a few bugs if the world is very large.

![image](https://github.com/user-attachments/assets/d0e67198-29b8-4181-893c-72a1353ddfe4)

**Comment by lumi-a** [comment]
#30 is now merged into main which was originally done to solve #26. Does it solve this issue, as well?

**Comment by Tim2othy** [comment]
seems all fixed  : )
