### ISSUE TITLE
Should we bother with large planets?

### ISSUE THREAD

**Issue by Tim2othy** [Tim2othy/spacegame#42]
Having really large planets `7000 < radius < 40_000` could be difficult to implement. 

Either the player only sees the planet if they are really close, or the camera has to be super zoomed out.
### Solutions I could see working:

1. Give the player the ability to Zoom in or out, and ability to toggle indicator for ships position on or off. Then they could zoom really far out and still know where they are.

2. Just not have giant planets.

### Considerations:
1. A game should be fun. If Giant planets are realistic but just not fun, there is little point in implementing them.
2. What could you do with the really zoomed out view? The only thing I can think of is using it as an obstacle so enemies can't shoot at you. But it seems like smaller planets are fine for this.

**Comment by lumi-a** [comment]
pygame.gfxdraw might not allow us to draw planets that are the size of >36 screens, but we might be able to find workarounds for that.

We could also have the camera focus on large planets once they're close-ish to the player. In general, it might be a good idea to focus on points of interest (enemies, mission goals) if they're close to the player.

**Comment by Tim2othy** [comment]
I don't think large planet's really work that well in 2d. Probably not worth the effort.
